import { ArrowDown, ArrowUp, ChevronRight, Download, Eye, ImagePlus, LayoutTemplate, Palette, Plus, RotateCcw, Send, Settings, SlidersHorizontal, Upload, Users, X } from 'lucide-react'
import { ChangeEvent, useRef, useState } from 'react'
import { ImageUploadField } from './ImageUploadField'
import { defaultContent } from '../../content/defaultContent'
import type { ProjectItem, ServiceItem, SiteContent, ThemeTokens } from '../../types/content'

type EditorView = 'menu' | 'hero' | 'services' | 'projects' | 'colors' | 'contact' | 'settings'
interface EditorPanelProps { content: SiteContent; setContent: (content: SiteContent) => void; onClose: () => void; onSave: () => void; onPublish: () => void; onPreview: () => void; onReset: () => void; onJumpTo: (id: string) => void }

const options: { id: EditorView; label: string; description: string; icon: typeof LayoutTemplate }[] = [
  { id: 'hero', label: 'Editar banner', description: 'Imagen, título y botones', icon: ImagePlus },
  { id: 'services', label: 'Editar servicios', description: 'Gestionar servicios', icon: SlidersHorizontal },
  { id: 'projects', label: 'Editar proyectos', description: 'Agregar / quitar', icon: LayoutTemplate },
  { id: 'colors', label: 'Editar colores', description: 'Paleta y estilos', icon: Palette },
  { id: 'contact', label: 'Editar contacto', description: 'Información y formulario', icon: Users },
  { id: 'settings', label: 'Configuración', description: 'SEO, datos legales, etc.', icon: Settings },
]

export function EditorPanel({ content, setContent, onClose, onSave, onPublish, onPreview, onReset, onJumpTo }: EditorPanelProps) {
  const [view, setView] = useState<EditorView>('menu')
  const importRef = useRef<HTMLInputElement>(null)
  const update = (next: SiteContent) => setContent(next)
  const updateHero = (field: keyof SiteContent['hero'], value: string) => update({ ...content, hero: { ...content.hero, [field]: value } })
  const updateTheme = (field: keyof ThemeTokens, value: string) => update({ ...content, theme: { ...content.theme, [field]: value } })
  const handleExport = () => { const blob = new Blob([JSON.stringify(content, null, 2)], { type: 'application/json' }); const url = URL.createObjectURL(blob); const link = document.createElement('a'); link.href = url; link.download = 'ifm-site-content.json'; link.click(); URL.revokeObjectURL(url) }
  const handleImport = async (event: ChangeEvent<HTMLInputElement>) => { const file = event.target.files?.[0]; if (!file) return; try { const parsed = JSON.parse(await file.text()) as SiteContent; if (!parsed.hero || !Array.isArray(parsed.services) || !Array.isArray(parsed.projects)) throw new Error('El archivo no tiene un esquema IFM válido.'); update(parsed) } catch (error) { window.alert(error instanceof Error ? error.message : 'No se pudo importar la configuración.') } finally { event.target.value = '' } }
  const select = (next: EditorView) => setView(next)
  return <aside className="editor-panel" aria-label="Panel Modo Edición"><div className="editor-topbar"><div><span className="editor-status-dot" /> <strong>Modo Edición</strong></div><button type="button" className="toggle-on" aria-label="Modo edición activo" onClick={onClose}><span /></button><button className="editor-close" type="button" onClick={onClose} aria-label="Cerrar modo edición"><X size={19} /></button></div>{view === 'menu' ? <><div className="editor-options">{options.map(({ id, label, description, icon: OptionIcon }) => <button type="button" className="editor-option" key={id} onClick={() => select(id)}><span className="editor-option-icon"><OptionIcon size={19} /></span><span><strong>{label}</strong><small>{description}</small></span><ChevronRight size={18} /></button>)}</div><div className="editor-primary-actions"><button type="button" className="button button-blue" onClick={onPublish}><Send size={17} /> Publicar cambios</button><button type="button" className="button button-pale" onClick={onPreview}><Eye size={17} /> Vista previa</button></div><div className="editor-secondary-actions"><button type="button" onClick={onSave}>Guardar cambios</button><button type="button" onClick={handleExport}><Download size={15} /> Exportar configuración</button><button type="button" onClick={() => importRef.current?.click()}><Upload size={15} /> Importar configuración</button><button type="button" onClick={onReset}><RotateCcw size={15} /> Restaurar valores predeterminados</button><input ref={importRef} hidden type="file" accept="application/json" onChange={(event) => { void handleImport(event) }} /></div></> : <div className="editor-detail"><button type="button" className="editor-back" onClick={() => setView('menu')}>← Volver a opciones</button>{view === 'hero' && <HeroEditor content={content} updateHero={updateHero} onJumpTo={onJumpTo} />}{view === 'services' && <ServicesEditor content={content} update={update} />}{view === 'projects' && <ProjectsEditor content={content} update={update} />}{view === 'colors' && <ColorsEditor theme={content.theme} updateTheme={updateTheme} onReset={() => update({ ...content, theme: { navy: '#163A5F', turquoise: '#14B8C4', coral: '#E66A4E', pearl: '#D9DEE5', gray: '#7B8792' } })} />}{view === 'contact' && <ContactEditor content={content} update={update} />}{view === 'settings' && <SettingsEditor content={content} update={update} />}</div>}</aside>
}

function EditorField({ label, value, onChange, multiline = false }: { label: string; value: string; onChange: (value: string) => void; multiline?: boolean }) { return <label className="editor-field">{label}{multiline ? <textarea value={value} rows={3} onChange={(event) => onChange(event.target.value)} /> : <input value={value} onChange={(event) => onChange(event.target.value)} />}</label> }

function HeroEditor({ content, updateHero, onJumpTo }: { content: SiteContent; updateHero: (field: keyof SiteContent['hero'], value: string) => void; onJumpTo: (id: string) => void }) {
  return <div><h2>Editar banner</h2><p className="editor-help">Los cambios se reflejan en la página mientras editas.</p><EditorField label="Título principal" value={content.hero.title} onChange={(value) => updateHero('title', value)} /><EditorField label="Título destacado" value={content.hero.highlight} onChange={(value) => updateHero('highlight', value)} multiline /><EditorField label="Texto de apoyo" value={content.hero.subtitle} onChange={(value) => updateHero('subtitle', value)} multiline /><EditorField label="Botón principal" value={content.hero.primaryCta} onChange={(value) => updateHero('primaryCta', value)} /><EditorField label="Botón secundario" value={content.hero.secondaryCta} onChange={(value) => updateHero('secondaryCta', value)} /><ImageUploadField label="Imagen de banner" source={content.hero.image} original={defaultContent.hero.image} position={content.hero.imagePosition} onSourceChange={(value) => updateHero('image', value)} onPositionChange={(value) => updateHero('imagePosition', value)} /><button type="button" className="editor-jump" onClick={() => onJumpTo('inicio')}>Ver banner en la página <ChevronRight size={16} /></button></div>
}

function reorderItem<T extends { id: string }>(items: T[], id: string, direction: -1 | 1): T[] {
  const index = items.findIndex((item) => item.id === id)
  const nextIndex = index + direction
  if (index < 0 || nextIndex < 0 || nextIndex >= items.length) return items
  const next = [...items]
  const [item] = next.splice(index, 1)
  next.splice(nextIndex, 0, item)
  return next
}

function ServicesEditor({ content, update }: { content: SiteContent; update: (content: SiteContent) => void }) {
  const [selected, setSelected] = useState(content.services[0]?.id ?? '')
  const current = content.services.find((service) => service.id === selected) ?? content.services[0]
  const addService = () => update({ ...content, services: [...content.services, { id: `service-${Date.now()}`, title: 'Nuevo servicio', description: 'Describe este servicio.', detail: 'Amplía el detalle de este servicio.', image: content.brand.logoMark, imagePosition: 'center', icon: 'container' }] })
  if (!current) return <div><h2>Editar servicios</h2><button type="button" className="button button-blue" onClick={addService}><Plus size={16} /> Agregar servicio</button></div>
  const updateCurrent = (field: keyof ServiceItem, value: string) => update({ ...content, services: content.services.map((service) => service.id === current.id ? { ...service, [field]: value } : service) })
  return <div><h2>Editar servicios</h2><div className="editor-list-tabs">{content.services.map((service) => <button type="button" className={service.id === current.id ? 'is-selected' : ''} key={service.id} onClick={() => setSelected(service.id)}>{service.title}</button>)}</div><EditorField label="Título" value={current.title} onChange={(value) => updateCurrent('title', value)} /><EditorField label="Descripción" value={current.description} onChange={(value) => updateCurrent('description', value)} multiline /><EditorField label="Detalle" value={current.detail} onChange={(value) => updateCurrent('detail', value)} multiline /><ImageUploadField label="Imagen" source={current.image} original={defaultContent.services.find((service) => service.id === current.id)?.image} position={current.imagePosition} onSourceChange={(value) => updateCurrent('image', value)} onPositionChange={(value) => updateCurrent('imagePosition', value)} /><div className="editor-reorder"><button type="button" onClick={() => update({ ...content, services: reorderItem(content.services, current.id, -1) })}><ArrowUp size={15} /> Subir</button><button type="button" onClick={() => update({ ...content, services: reorderItem(content.services, current.id, 1) })}><ArrowDown size={15} /> Bajar</button></div><button type="button" className="editor-danger" onClick={() => update({ ...content, services: content.services.filter((service) => service.id !== current.id) })}>Eliminar servicio</button><button type="button" className="editor-add" onClick={addService}><Plus size={16} /> Agregar servicio</button></div>
}

function ProjectsEditor({ content, update }: { content: SiteContent; update: (content: SiteContent) => void }) {
  const [selected, setSelected] = useState(content.projects[0]?.id ?? '')
  const current = content.projects.find((project) => project.id === selected) ?? content.projects[0]
  const updateCurrent = (field: keyof ProjectItem, value: string | boolean) => current && update({ ...content, projects: content.projects.map((project) => project.id === current.id ? { ...project, [field]: value } : project) })
  const addProject = () => { const id = `project-${Date.now()}`; update({ ...content, projects: [...content.projects, { id, title: 'Nuevo proyecto', category: 'Capacidad demostrativa', location: 'Ubicación editable', description: 'Descripción editable.', image: content.brand.logoMark, imagePosition: 'center', isDemo: true }] }); setSelected(id) }
  return <div><h2>Editar proyectos</h2><div className="editor-list-tabs">{content.projects.map((project) => <button type="button" className={project.id === current?.id ? 'is-selected' : ''} key={project.id} onClick={() => setSelected(project.id)}>{project.title}</button>)}</div>{current && <><EditorField label="Título" value={current.title} onChange={(value) => updateCurrent('title', value)} /><EditorField label="Categoría" value={current.category} onChange={(value) => updateCurrent('category', value)} /><EditorField label="Ubicación" value={current.location} onChange={(value) => updateCurrent('location', value)} /><EditorField label="Descripción" value={current.description} onChange={(value) => updateCurrent('description', value)} multiline /><ImageUploadField label="Imagen" source={current.image} original={defaultContent.projects.find((project) => project.id === current.id)?.image} position={current.imagePosition} onSourceChange={(value) => updateCurrent('image', value)} onPositionChange={(value) => updateCurrent('imagePosition', value)} /><label className="editor-check"><input type="checkbox" checked={current.isDemo} onChange={(event) => updateCurrent('isDemo', event.target.checked)} /> Marcar como ejemplo editable</label><div className="editor-reorder"><button type="button" onClick={() => update({ ...content, projects: reorderItem(content.projects, current.id, -1) })}><ArrowUp size={15} /> Subir</button><button type="button" onClick={() => update({ ...content, projects: reorderItem(content.projects, current.id, 1) })}><ArrowDown size={15} /> Bajar</button></div><button type="button" className="editor-danger" onClick={() => update({ ...content, projects: content.projects.filter((project) => project.id !== current.id) })}>Eliminar proyecto</button></> }<button type="button" className="editor-add" onClick={addProject}><Plus size={16} /> Agregar proyecto</button></div>
}

function ColorsEditor({ theme, updateTheme, onReset }: { theme: ThemeTokens; updateTheme: (field: keyof ThemeTokens, value: string) => void; onReset: () => void }) { return <div><h2>Editar colores</h2><p className="editor-help">Ajusta el color y revísalo en vivo. La paleta oficial siempre puede restaurarse.</p>{(Object.keys(theme) as (keyof ThemeTokens)[]).map((key) => <label className="color-field" key={key}><span>{key}</span><input type="color" value={theme[key]} onChange={(event) => updateTheme(key, event.target.value)} /><input value={theme[key]} onChange={(event) => updateTheme(key, event.target.value)} /></label>)}<button type="button" className="editor-add" onClick={onReset}>Restaurar paleta oficial IFM</button></div> }

function ContactEditor({ content, update }: { content: SiteContent; update: (content: SiteContent) => void }) { const updateContact = (field: keyof SiteContent['contact'], value: string) => update({ ...content, contact: { ...content.contact, [field]: value } }); return <div><h2>Editar contacto</h2><p className="editor-help">Estos datos se muestran en el encabezado, formulario y pie de página.</p><EditorField label="Teléfono" value={content.contact.phone} onChange={(value) => updateContact('phone', value)} /><EditorField label="Correo electrónico" value={content.contact.email} onChange={(value) => updateContact('email', value)} /><EditorField label="WhatsApp" value={content.contact.whatsapp} onChange={(value) => updateContact('whatsapp', value)} /><EditorField label="Dirección visible" value={content.contact.address} onChange={(value) => updateContact('address', value)} /><EditorField label="Descripción del pie" value={content.footer.description} onChange={(value) => update({ ...content, footer: { ...content.footer, description: value } })} multiline /></div> }

function SettingsEditor({ content, update }: { content: SiteContent; update: (content: SiteContent) => void }) { return <div><h2>Configuración</h2><EditorField label="Título del sitio" value={content.site.title} onChange={(value) => update({ ...content, site: { ...content.site, title: value } })} /><EditorField label="Meta descripción" value={content.site.description} onChange={(value) => update({ ...content, site: { ...content.site, description: value } })} multiline /><EditorField label="URL canónica" value={content.site.canonical} onChange={(value) => update({ ...content, site: { ...content.site, canonical: value } })} /><EditorField label="Razón social" value={content.legalName} onChange={(value) => update({ ...content, legalName: value })} /><EditorField label="RUC" value={content.ruc} onChange={(value) => update({ ...content, ruc: value })} /><EditorField label="Domicilio fiscal" value={content.fiscalAddress} onChange={(value) => update({ ...content, fiscalAddress: value })} multiline /><p className="editor-note">El editor demo no publica en un servidor. Exporta la configuración para conectarla luego a un CMS o API.</p></div> }
